routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');


Auth::routes();

Route::get('entries/user/{user_id?}', 'EntriesController@index');
Route::post('entries/hideOrShowTweet', 'EntriesController@hideOrShowTweet');
Route::resource('entries', 'EntriesController');

app/Entry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    protected $fillable = [
        'title', 'content', 'user_id'
    ];

    protected $casts = [
        'user_id' => 'integer'
    ];


    public function user(){
        return $this->belongsTo('App\User');

    }

}

app/Tweet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tweet extends Model
{
    protected $fillable = [
        'tweet_id',
    ];

    public function user(){
        return $this->belongsTo('App\User');

    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'id' => 'integer'
    ];

    public function entries()
    {
        return $this->hasMany('App\Entry');
    }

    public function hiddenTweets()
    {
        return $this->hasMany('App\Tweet')->where('hidden', 1);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EntriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Response;
use App\Entry;
use App\User;
use App\Tweet;
use DB;
//use ReliqArts\Thujohn;
use ReliqArts\Thujohn\Twitter\Facades\Twitter;



class EntriesController extends Controller
{
    /**
     * Check for user auth
     *
     * @return void
     */

    public function AuthCheck() {
        if (!Auth::check()) {
            abort(403, 'Unauthorized action');
        }
    }

    /**
     * Check entry ownership
     *
     * @return void
     */
    public function OwnerCheck($entry){

        if ($entry->user_id !== Auth::user()->id) {
            abort(403, 'You are not allowed to edit or delete this entry');
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function hideOrShowTweet(Request $request) {

        $id = $request->input('id');

        $tweet = Tweet::FirstOrNew(['tweet_id' => $id]);

        if ($tweet->exists) {
            $tweet->hidden = (!$tweet->hidden);
        }
        else {
          $tweet->tweet_id = $id;
          $tweet->hidden = true;
          $tweet->user_id = Auth::user()->id;
        }
        //dd($tweet);
        $tweet->save();
        return Response::json($tweet->hidden);
    }

    public function index($user = null)
    {
        if ($user == null)  {
          if (Auth::check()) {
              $user = Auth::user()->id;
          }
          else {
              abort(403, 'Unauthorized action');
          }
        }

        $user = User::FindOrFail($user);

        $entries = Entry::when($user, function ($q) use ($user) {
            return $q->where('user_id', $user->id);
        })->with('user')->orderby('created_at', 'desc')->paginate(5);

        // get tweets from user time line
        $tweets = collect(json_decode(Twitter::getUserTimeline(['screen_name' => $user->twitter_handle, 'count' => 5, 'format' => 'json'])));
        // get hiodden tweets for current logged in user
        $hiddenTweets = $user->hiddenTweets()->get();

        // iterate over timeline to check if we nee dto hide some tweet
        $tweets = $tweets->map(function ($t) use ($hiddenTweets) {
            $t->hidden  = $hiddenTweets->contains('tweet_id', $t->id_str);
            return $t;
        });


      return view('entries-index', compact('entries', 'user', 'tweets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->AuthCheck();
        $entry = new Entry;
        return view('entries-edit', compact('entry'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $e = new Entry;
        $e->title =  $request->input('title');
        $e->content = $request->input('content');
        $e->user_id = Auth::user()->id;
        $e->save();

        Session::flash('success', 'Entries created');

        return redirect()->route('entries.index');

//        return response()->view('index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entry = Entry::FindOrFail($id);
        //dd($entry);
        return view('entries-show', compact('entry'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->AuthCheck();

        $entry = Entry::FindOrFail($id);

        $this->OwnerCheck($entry);


        return view('entries-edit', compact('entry'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->AuthCheck();

        $entry = Entry::FindOrFail($id);


        $this->OwnerCheck($entry);

        $entry->title = $request->input('title');
        $entry->content = $request->input('content');

        $entry->save();



        return redirect()->route('entries.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->AuthCheck();

        $entry = Entry::FindOrFail($id);

        $this->OwnerCheck($entry);

        $entry->delete();

        return Response::json(true);
    }
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entry;
use App\User;


class IndexController extends Controller
{

    public function index()
    {
        //
        // At fiurst, I'm getting last 3 entries for EACH user
        //

        // $entries = collect([]);
        // $users = User::has('entries')->get();
        // foreach($users as $u) {
        //   $e = Entry::with('user')->where('user_id', $u->id)->orderby('created_at', 'desc')->limit(3)->get();
        //   foreach($e as $entry)
        //     $entries->push($entry);
        // }


        // but reading againg, I realize that were the last 3 entries for ALL users, so is much more simple

        $entries = Entry::with('user')->orderby('created_at', 'desc')->limit(3)->get()->paginate(5);

        return view('index', compact('entries'));
    }
}

resources/views/entries-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form class="form-horizontal" action="{{$entry->exists ? route('entries.update', $entry->id) : route('entries.store') }}"
                method="POST">
                <fieldset>
                    @if($entry->exists)
                        <legend>Edit entry</legend>
                        <input type="hidden" name="_method" value="PATCH">
                    @else
                    <legend>Create entry</legend>
                    @endif
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="textinput">Title</label>
                      <div class="col-md-8">
                        <input id="title" name="title" type="text"  class="form-control input-md" required="" value="{{$entry->title}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-md-4 control-label" for="content">Content</label>
                      <div class="col-md-12">
                        <textarea required="" class="form-control" id="content" name="content" rows="10" cols="50">{{$entry->content}}</textarea>
                      </div>
                    </div>
                    {{ csrf_field() }}
                    <button class="btn btn-success" type="submit">Save</button>
                </fieldset>
                </form>
        </div>
    </div>
</div>
@endsection

resources/views/entries-index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @isset($user)
                <div> <h2>Entries for user {{$user->name}} </h2></div>
            @endif
            @empty($entries)
                <h1>No entries to display</h1>
            @else
                <br>
                @each('entry-detail-partial', $entries, 'entry')
            @endempty
            {{$entries->links()}}
            <a href="/">Back to home</a>
        </div>

        <div class="col-xs-4 col-sm-4 :col-md-4 col-lg-4">
            <div><h3>Latest tweets</h3></div>
            <div id="tweets">
                  @empty($tweets)
                    <h1>No tweets to display</h1>
                  @else
                    <p>Showing latest  tweets for {{$user->twitter_handle}} twitter account</p>
                    <br>
                    @foreach($tweets as $tweet)
                        {{--  if tweet owner is logged user, allow to hide.show tweets options  --}}
                        @if(Auth::check() && Auth::user()->id == $user->id)
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                <p class="card-text">{{$tweet->text}}</p>
                                    @if($tweet->hidden)
                                    <a id="btnShowHide{{$tweet->id_str}}" class="btnHideTweet btn btn-secondary btn-danger" data-id="{{$tweet->id_str}}"  href="#">Show tweet</a>
                                    @else
                                    <a id="btnShowHide{{$tweet->id_str}}" class="btnHideTweet btn btn-secondary btn-success" data-id="{{$tweet->id_str}}" href="#">Hide tweet</a>
                                    @endif
                                </div>
                            </div>
                            </br>
                        @else
                          {{--  else, check if tweet was not set hidden by its owner  --}}
                          @if(!$tweet->hidden)
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                <p class="card-text">{{$tweet->text}}</p>
                                </div>
                            </div>
                            </br>
                          @endif
                        @endif

                    @endforeach
                  @endempty
            </div>
        </div>

    </div>
</div>
@endsection
@section('document-ready')
    @include('entry-delete-js-partial')
    @include('tweet-delete-js-partial')
@endsection

resources/views/entries-show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2><a href="/entries/{{$entry->id}}/show">{{$entry->title}}</a></h2>
            @if(Auth::check())
                @if(Auth::user()->id == $entry->user_id)
                <div class="row">
                    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                        <a class="btn btn-small  btn-success" href="/entries/{{$entry->id}}/edit" role="button">Edit</a>
                    </div>
                </div>
                @endif
            @endif

            <small>
                {{$entry->created_at}} by <a href="/entries/{{$entry->user_id}}">{{$entry->user->name}}</a>
            </small>
            <p>
                {{htmlspecialchars(nl2br($entry->content))}}
            </p>
        </div>
    </div>
</div>
@endsection

resources/views/entry-delete-js-partial.blade.php
    // function to handle entry deletion confirmation and execution
    $(".btnDeleteEntry").unbind('click').bind('click', function (e) {
        e.preventDefault();
        if (!confirm('Are you sure to delete this entry?')) {
            return false;
        }
        // get  element clicked data
        var elem = $(this);
        var id = elem.data('id');
        //run ajax request
        $.ajax({
            url: '/entries/'+id,
            type: 'DELETE',
            //data: {id:  id},
            cache: false,
            success: function (data) {
                // reload page
                location.reload();
                return true;
            },
            error: function (data) {
                console.log('Error: '+data)
                return false;
            }
        });
    });

resources/views/entry-detail-partial.blade.php
<div>
<h2><a href="/entries/{{$entry->id}}/">{{$entry->title}}</a></h2>
@if(Auth::check())
  @if(Auth::user()->id == $entry->user_id)
    <div class="row">
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
            <a class="btn btn-small  btn-success" href="/entries/{{$entry->id}}/edit" role="button">Edit</a>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
            <a class="btnDeleteEntry btn btn-small btn-danger" href="#" data-id="{{$entry->id}}" role="button">Delete</a>
        </div>
    </div>
  @endif
@endif

<small>
    {{$entry->created_at}} by <a href="/entries/user/{{$entry->user_id}}">{{$entry->user->name}}</a>
</small>


{{--  <p>
{{$entry->content}}
</p>  --}}

</div>
</br>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @empty($entries)
              <h1>No entries to display</h1>
            @else
              <h3>Showing latest 3 entries of ALL users </h3>
              <br>
              @each('entry-detail-partial', $entries, 'entry')
              </br>
              {{$entries->links()}}
              {{--  <a href="/entries">Back to entries list</a>  --}}
            @endempty

        </div>
    </div>
</div>
@endsection
@section('document-ready')
    @include('entry-delete-js-partial')
@endsection
</script>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('entries.create') }}">{{ __('Create entry') }}</a>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        @yield('document-ready')
    });
    </script>
</html>

resources/views/tweet-delete-js-partial.blade.php
    // function to handle tweet hidding/unhidding button click
    $(".btnHideTweet").unbind('click').bind('click', function (e) {
        e.preventDefault();
        // get  element clicked data
        var elem = $(this);
        var id = elem.data('id');
        //run ajax request
        $.ajax({
            url: '/entries/hideOrShowTweet',
            type: 'POST',
            data: {id:  id},
            cache: false,
            success: function (hidden) {
                // Change element data accordding tweet status returned
                if (hidden) {
                    elem.toggleClass("btn-success");
                    elem.toggleClass("btn-danger");
                    elem.html('Show tweet');
                }
                else {
                    elem.toggleClass("btn-success");
                    elem.toggleClass("btn-danger");
                    elem.html('Hide tweet');
                }
                return true;
            },
            error: function (data) {
                console.log('Error: '+data)
                return false;
            }
        });
    });